### ISSUE TITLE
Hypothetical Weapon Upgrade System

### ISSUE THREAD

**Issue by Amket** [SmartlyDressedGames/Unturned-4.x-Community#192]
There is a video version of this same paragraph here:
https://www.youtube.com/watch?v=Kb7dbCJoxHE&t=226s
(Skip to 14:50)

In Unturned, after getting an assault rifle, there is little progression left to be had afterward, and the little room for progress left is really nothing more than hoping for a rare item spawn. I've been tossing some ideas around, and I think this would be the best solution to make progressing past and to an assault rifle not only more in depth and interesting, but also more consistent. The ability to break down or "Salvage" weapons in order to make newer, better ones (in the same caliber).

Here is a Hypothetical table for the "Ranger" caliber of guns:
![weapon upgrade table5](https://user-images.githubusercontent.com/36281390/36347438-253667b8-144f-11e8-85ed-bc81a58b639d.png)

Essentially, every weapon can be broken down into the amount of action parts, barrel and furniture that are required to craft said weapon. Those if there are enough of those parts to craft a new weapon, the player can do so. Barrels, action parts and furniture can be used to make attachments like suppressors, grips and sights.

*Note: I intentionally lowered the amount of barrel and furniture parts needed to make the later weapons such as the Nykorev, as to allow players to have more options with attachment customization for other weapons.

As these parts are all "Ranger" type, I was thinking about the ability to make carbine weapons, such as instead of the ak-47 that costs 2 ranger action parts, 2 ranger barrels and 2 furniture parts to craft, having the ability to craft an ak-47 "Military Carbine", a sort of hybrid between the maplestrike and ak, able to fire military magazines, costing 2 ranger and 1 military action parts, 2 ranger barrels and 2 furniture parts to craft. I'm a bit on the fence about this idea, it would mean that different caliber parts can be combined in order to craft new weapons, but my fear is that it wouldn't be used very often.

Regardless, I think this would be a great way to allow players to fairly and consistently upgrade their weapons, as well as giving players incentive to killing other players in order to craft new, exciting weapons, instead of having more of the same old ones.

**Comment by SnowEdwin** [comment]
i'm assuming you haven't seen devlog 5? because if you had you'd've seen this: 
![if this shows up then it's because i didn't know if it would print as text and it probably links to the photo i'm talking about which makes me tilted](https://user-images.githubusercontent.com/33387246/36348872-fa7a0924-142d-11e8-9393-581fa58816e3.png)
and from what i've read it either changes a number of things you suggested or downright makes it redundant. so...eh?

**Comment by Amket** [comment]
This contradicts nothing I've said. I never said that crafted weapons can't be given attachments, all I said is that weapon parts can be used to craft newer weapons and new weapon attachments.

**Comment by SnowEdwin** [comment]
yeah, but then what does this mean for the number of barrels required to craft a new gun? would a nykorev still take 3 barrels, or would it just need one specialized barrel? what happens to "action parts" and "furniture", since the attachments split them up into several different pieces?

it might not make your suggestion redundant, but it puts quite a bit of it into question.

**Comment by SDGNelson** [comment]
I do intend to have craftable parts especially bullets, for example building a custom stock if you can't find a military one. I don't think I would go so far as to allow crafting the full-on factory-grade models, however.

That aside: this issues board isn't intended for suggestion posts, rather to track my development tasks for 4 (and made public so that you can see how it's coming). [The forums](https://forum.smartlydressedgames.com/c/unturned-4) would be better suited for this sort of post.
