### ISSUE TITLE
Unturned Zwei car breaks

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-4.x-Community#258]
How will car breaks work? That's essential for drifting

**Comment by TheRealTamama** [comment]
Hi, im a content creator in Unturned 3.0 and i have an addition question:
 "Will there be detailed visual component to cars like being able to see the disk breaks, springs,etc?"

Oh and if you don't mind suggestions, I think having just the disk breaks would be very well accepted
in the community. Especially if the front breaks can follow the steering of the wheels. This small detail alone gives the car a much needed realistic look.

**Comment by MoltonMontro** [comment]
> Oh and if you don't mind suggestions,

Suggestions should be posted on one of the official forums. The GitHub repository isn't the proper place for suggestions (nor most inquiries).

**Comment by SDGNelson** [comment]
Molton's right, but in short I'll say:

The hatchback doesn't have animated brakes because they aren't very visible on that vehicle, but it would be super easy to do in a mod without requiring changes on my end. Future vehicles might make more sense to show them like a dune buggy.

Googling "zwei car breaks" doesn't come up with much so I'm not sure which you're talking about, but they're pretty configurable. Today or tomorrow I'm actually splitting up the animations for pedal brakes and emergency (drift) brake so there's that level of control too.
